project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as users_views
from search import views as search_views
from forum import views as forum_views
from logs import views as logs_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', users_views.register, name= 'signup'),
    path('profile/', users_views.profile, name= 'profile'),
    path('signin/', auth_views.LoginView.as_view(redirect_authenticated_user = True,
        template_name = 'users/signin.html'), name= 'signin'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'website/logout.html'), name= 'logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name = 'users/password_reset.html'), 
        name= 'password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name = 'users/password_reset_done.html'), 
        name= 'password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view
        (template_name = 'users/password_reset_confirm.html'), name= 'password_reset_confirm'),
     path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view
        (template_name = 'users/password_reset_complete.html'), name= 'password_reset_complete'),
    path('change-password/', users_views.change_password, name= 'change_password'),
    path('search/', search_views.search, name= 'searchpage'),
    path('advanced-search/', search_views.advanced_search, name= 'advanced_searchpage'),
    path('details/<str:cve_id>/', search_views.details, name= 'detailspage'),
    path('pdf/<str:cve_id>/', search_views.get_pdf, name= 'pdfpage'),
    path('advanced-search-details/<str:cve_id>/', search_views.advancedsearch_details, name= 'advanceddetailspage'),
    path('forum/', forum_views.forum, name= 'forumpage'),
    path('forum-create/', forum_views.thread_create, name= 'forumcreate'),
    path('forum/<int:thread_id>/', forum_views.thread_detail, name= 'forumidspage'),
    path('forum/<int:thread_id>/edit/', forum_views.thread_edit, name= 'forumedit'),
    path('forum/<int:thread_id>/delete/', forum_views.thread_delete, name= 'forumdelete'),
    path('forum/<int:thread_id>/add-comment/', forum_views.add_comments, name= 'addcomment'),
    path('forum/<int:comment_id>/edit-comment/', forum_views.edit_comments, name= 'editcomment'),
    path('forum/<int:comment_id>/delete-comment/', forum_views.delete_comments, name= 'deletecomment'),
    path('forum/<int:comment_id>/add-reply/', forum_views.add_reply, name= 'addreply'),
    path('forum/<int:reply_id>/edit-reply/', forum_views.edit_reply, name= 'editreply'),
    path('forum/<int:reply_id>/delete-reply/', forum_views.delete_reply, name= 'deletereply'),
    path('history/', logs_views.history, name= 'historypage'),
    path('updates/', search_views.updates, name= 'updatepage'),
    path('', include('website.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Thread(models.Model):
    thread_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    creation = models.DateTimeField(auto_now_add=True)
    
class Comment(models.Model):
    thread_id = models.ForeignKey(Thread, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    creation = models.DateTimeField(auto_now_add=True)

class Reply(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    creation = models.DateTimeField(auto_now_add=True)

forum/forms.py
from django import forms
from .models import Thread, Comment, Reply

class ThreadForm(forms.ModelForm):
    class Meta:
        model = Thread
        fields = ['title', 'content']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ['content']

forum/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Thread, Comment, Reply
from .forms import ThreadForm, CommentForm, ReplyForm

# Create your views here.

@login_required
def thread_create(request):
    if request.method == 'POST':
        form = ThreadForm(request.POST)

        if form.is_valid():
            thread = form.save(commit=False)
            thread.author = request.user
            thread.save()

            return redirect('forumidspage', thread_id=thread.pk)
    else:
        form = ThreadForm()

    return render(request, 'forum/thread_create.html', {'form':form})


@login_required
def thread_edit(request, thread_id):
    thread = get_object_or_404(Thread, thread_id=thread_id)
    if request.user == thread.author:
        if request.method == 'POST':
            form = ThreadForm(request.POST, instance=thread)
            if form.is_valid():
                form.save()
                return redirect('forumidspage', thread_id=thread.pk)
        else:
            form = ThreadForm(instance=thread)

        
        return render(request, 'forum/thread_edit.html', {'form':form, 'thread':thread})
    else:
        return redirect('forumidspage', thread_id=thread.pk)


@login_required
def thread_delete(request, thread_id):
    thread = get_object_or_404(Thread, thread_id=thread_id)
    if request.user == thread.author:
        if request.method == 'POST':
            thread.delete()
            return redirect('forumpage')
        else:
            return render(request, 'forum/thread_delete.html', {'thread': thread})
    else:
        return redirect('forumpage')


@login_required
def add_comments(request, thread_id):
    thread = get_object_or_404(Thread, thread_id=thread_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.thread_id = thread
            comment.author = request.user
            comment.save()

            return redirect('forumidspage', thread_id=thread.pk)
    else:
        form = CommentForm()
    
    return render(request, 'forum/add_comments.html', {'thread': thread, 'commentForm':form})


@login_required
def edit_comments(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user == comment.author:
        if request.method == 'POST':
            form = CommentForm(request.POST, instance=comment)
            if form.is_valid():
                form.save()
                return redirect('forumidspage', thread_id=comment.thread_id.pk)
        else:
            form = CommentForm(instance=comment)
        
        return render(request, 'forum/comment_edit.html', {'form':form, 'comment':comment})
    else:
        return redirect('forumidspage', thread_id=comment.thread_id.pk)

@login_required    
def delete_comments(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user == comment.author:
        if request.method == 'POST':
            thread_id = comment.thread_id.pk
            comment.delete()

            return redirect('forumidspage', thread_id=thread_id)
        else:
            return render(request, 'forum/comment_delete.html', {'comment': comment})
    else:
        return redirect('forumpage')

@login_required
def add_reply(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.method == 'POST':
        form = ReplyForm(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.comment = comment
            reply.author = request.user
            reply.save()

            comment.save()
            return redirect('forumidspage', thread_id=comment.thread_id.pk)
    else:
        form = ReplyForm()
    
    return render(request, 'forum/add_reply.html', {'form':form, 'comment':comment})

@login_required
def edit_reply(request, reply_id):
    reply = get_object_or_404(Reply, pk=reply_id)
    if request.method == 'POST':
        form = ReplyForm(request.POST,  instance=reply)
        if form.is_valid():
            form.save()
            return redirect('forumidspage', thread_id=reply.comment.thread_id.pk)
    else:
        form = ReplyForm(instance=reply)
    
    return render(request, 'forum/edit_reply.html',{'form':form, 'reply':reply})

@login_required
def delete_reply(request, reply_id):
    reply = get_object_or_404(Reply, pk=reply_id)
    comment = reply.comment
    if request.method == 'POST':
        reply.delete()

        comment.save()

        return redirect('forumidspage', thread_id=reply.comment.thread_id.pk)
    
    return render(request, 'forum/delete_reply.html',{'reply':reply})

@login_required
def forum(request):
    threads = Thread.objects.all()
    return render(request, 'forum/forum.html', {'threads': threads})

@login_required
def thread_detail(request, thread_id):
    thread = get_object_or_404(Thread, thread_id=thread_id)
    return render(request, 'forum/thread.html', {'thread': thread})

forum/templates/forum/add_comments.html
{% extends "website/base.html" %}
{% load crispy_forms_tags %}
{% block content %}


<h2 class="text-white">Add Comment</h2>

<div class="addcomment-section text-center">
    {% if user.is_authenticated %}
        <form method="POST">
            {% csrf_token %}
            {{ commentForm|crispy }}
            <button class="btn btn-dark btn-submit" type="submit">Add Comment</button>
            <a class="text-black" href="{% url 'forumidspage' thread.thread_id %}">Cancel</a>

        </form>
    {% endif %}
</div>

{% endblock content %}

forum/templates/forum/add_reply.html
{% extends "website/base.html" %}
{% load crispy_forms_tags %}
{% block content %}


<h1>Add Reply</h1>

<div class="addreply-section text-center">
    {% if user.is_authenticated %}
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-dark btn-submit" type="submit">Add Reply</button>
            <a class="text-black" href="{% url 'forumidspage' comment.thread_id.pk %}">Cancel</a>

        </form>
    {% endif %}
</div>

{% endblock content %}

forum/templates/forum/comment_delete.html
{% extends "website/base.html" %}
{% block content %}

    <h1 class="text-white">Confirm Delete Comment</h1>

    <div class="commentdelete-section text-center">
        <h3>Are you sure you want to delete the comment "{{ comment.content }}"? </h3>
        <br>
        <form method="POST">
            {% csrf_token %}
            <button class="btn btn-dark btn-submit" type="submit">Yes, Delete</button>
            <a class="text-black" href="{% url 'forumidspage' comment.thread_id.pk %}">Cancel</a>
        </form>
    </div>

{% endblock content %}

forum/templates/forum/comment_edit.html
{% extends "website/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <h1 class="text-white">Edit Comment</h1>

    <div class="commentedit-section text-center">
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-submit btn-dark">Update</button>
            <a class="text-black" href="{% url 'forumidspage' comment.thread_id.pk %}">Cancel</a>

        </form>
    </div>

{% endblock content %}

forum/templates/forum/delete_reply.html
{% extends "website/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <h1 class="text-white">Confirm Delete Reply</h1>

    <div class="replydelete-section text-center">
        <h3>Are you sure you want to delete the reply "{{ reply.content }}"?</h3>
        <br>
        <form method="post">
            {% csrf_token %}
            <button class="btn btn-dark btn-submit" type="submit">Delete</button>
            <a href="{% url 'forumidspage' reply.comment.thread_id.pk %}">Cancel</a>
        </form>
    </div>

{% endblock content %}

forum/templates/forum/edit_reply.html
{% extends "website/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<h1 class="text-white">Edit Reply</h1>

    <div class="replyedit-section text-center">
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-submit btn-dark">Update</button>
            <a class="text-black" href="{% url 'forumidspage' reply.comment.thread_id.pk %}">Cancel</a>
        </form>
    </div>

{% endblock content %}

forum/templates/forum/forum.html
{% extends "website/base.html" %}
{% block content %}

    <div class="page-title">DISCUSSIONS FORUM</div>
    <div class="discussion-container">
        <div class="discussion-header">
            <div class="search-field">
                <input type="text" placeholder="Search for discussions...">
            </div>
            <button class="threadsearch-btn btn btn-dark">
                <i class="fas fa-search"></i>
            </button>
            
            <button class="create-button" onclick=window.location.href="{% url 'forumcreate' %}">+ Discussion</button>
        </div>

        <div class="announcement-section">
            <div class="announcement-item">
                <h>Latest Announcements</h>
            </div>
        </div>    
        {% for thread in threads %}
            {% if thread.author.is_superuser %}
            <div class="discussion-item{{ forloop_counter }}"> 
                    <a href="{% url 'forumidspage' thread.thread_id %}">{{ thread.title }}</a>

                    <div class="preview">{{ thread.content|truncatewords:10 }}</div>
            </div>
            
            {% endif %}
      
        {% empty %}
            <div class="discussion-item">
                <a>No threads available.</a>
            </div>

        {% endfor %}    
        
        <br>
        <div class="announcement-section">
            <div class="announcement-item">
                <h>Latest Discussions</h>
            </div>
        </div>
   
        {% for thread in threads %}
            {% if not thread.author.is_superuser %}
                <div class="discussion-item{{ forloop_counter }}"> 
                    <a href="{% url 'forumidspage' thread.thread_id %}">{{ thread.title }}</a>

                    <div class="preview">{{ thread.content|truncatewords:10 }}</div>
                </div>
            {% endif %}
                
        {% empty %}
        <div class="discussion-item">
            <a>No threads available.</a>
        </div>
        {% endfor %}
    </div>
    <br>
{% endblock content %}

forum/templates/forum/thread.html
{% extends "website/base.html" %}
{% block content %}
    
    <div class="page-title">Thread Detail</div>
    <div class="comments-container">
        <a href="{% url 'forumpage' %}" class="text-white"><i class="fas fa-arrow-left"></i> Go to Discussions</a>

        <div class="sticky-header text-white">
            <h2>{{ thread.title }}</h2>
            <p>{{ thread.content|linebreaksbr }}</p>
            <br>
            <p><strong>Author: </strong><img src="{{ thread.author.profile.image.url }}" alt="User" class="comment-profile-pic">{{ thread.author }}</p>
            <p><strong>Creation Date:</strong> {{ thread.creation }}</p>
            {% if user.is_authenticated and user == thread.author %}
                <a href="{% url 'forumedit' thread.thread_id %}" class="icon-button edit-button"><i class="fas fa-pencil-alt"></i></a>
                <a href="{% url 'forumdelete' thread.thread_id %}" class="icon-button delete-button"><i class="fas fa-trash"></i></a>
            {% endif %}
        </div>

        <div class="add-comment-container">
            <input placeholder="Add a comment..." class="comment-input" onclick=window.location.href="{% url 'addcomment' thread.thread_id %}"></input>
        </div>
        
        <br>
        {% for comment in thread.comment_set.all %}
        <div class="comments-list{ forloop_counter }">
            <div class="comment">
                <img src="{{ comment.author.profile.image.url }}" alt="User" class="comment-profile-pic">
                <div class="comment-body">
                    <span class="comment-text">{{ comment.author }}: {{ comment.content }}</span>
                </div>
                <span class="comment-timestamp">{{ comment.creation }}</span>
                {% if user.is_authenticated and user == comment.author %}
                    <a href="{% url 'editcomment' comment.pk %}" class="icon-button edit-button"><i class="fas fa-pencil-alt"></i></a>
                    <a href="{% url 'deletecomment' comment.pk %}" class="icon-button delete-button"><i class="fas fa-trash"></i></a>
                {% endif %}
                <button class="reply-button" onclick=window.location.href="{% url 'addreply' comment.id %}">Reply</button>    
            </div>
            
            {% for reply in comment.reply_set.all %}
            <div class="replies-section{ forloop_counter }">
                <div class="reply text-white">
                    <img src="{{ comment.author.profile.image.url }}" alt="User" class="comment-profile-pic">
                    <span class="reply-body">{{ reply.author }}: {{ reply.content }} </span>
                    <span class="comment-timestamp">{{ reply.creation }}</span>
                    {% if user.is_authenticated and user == reply.author %}
                        <a href="{% url 'editreply' reply.pk %}" class="icon-button edit-button"><i class="fas fa-pencil-alt"></i></a>
                        <a href="{% url 'deletereply' reply.pk %}" class="icon-button delete-button"><i class="fas fa-trash"></i></a>
                    {% endif %}
                </div>
                {% endfor %}
                <br>
            </div>

        {% endfor %}

        
        <div class="separating-line"></div>
        
    </div>

{% endblock content %}

forum/templates/forum/thread_create.html
{% extends "website/base.html" %}
{% load crispy_forms_tags %}
{% block content %}


<h2 class="text-white">Create a New Thread</h2>

<div class="threadcreate-section text-center">
    {% if user.is_authenticated %}
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-dark btn-submit" type="submit">Create</button>
            <a class="text-black" href="{% url 'forumpage' %}">Cancel</a>

        </form>
    {% endif %}
</div>

{% endblock content %}

forum/templates/forum/thread_delete.html
{% extends "website/base.html" %}
{% block content %}

    <h1 class="text-white">Delete Thread</h1>

    <div class="threaddelete-section text-center">
        <h3>Are you sure you want to delete the thread "{{ thread.title }}"?</h3>
        <br>
        <form method="POST">
            {% csrf_token %}
            <button class="btn btn-dark btn-submit" type="">Yes, Delete</button>
            <a class="text-black" href="{% url 'forumidspage' thread.thread_id %}">Cancel</a>
        </form>
    </div>

{% endblock content %}

forum/templates/forum/thread_edit.html
{% extends "website/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <h1 class="text-white">Edit Thread</h1>

    <div class="threadedit-section text-center">
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-submit btn-dark">Update</button>
            <a class="text-black" href="{% url 'forumidspage' thread.thread_id %}">Cancel</a>
        </form>
    </div>

{% endblock content %}